# Generated by Django 5.1.3 on 2024-11-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=25)),
                ('First_Name', models.CharField(max_length=25)),
                ('Middle_Name', models.CharField(max_length=25)),
                ('Last_Name', models.CharField(max_length=25)),
                ('Date_of_Birth', models.DateField()),
                ('Mobile_Number', models.IntegerField()),
                ('Email_Address', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=60)),
            ],
        ),
    ]
